! frr-ce2 — SP lab Customer Edge (FRR 9.x)
! Loopback: 10.2.0.9/32
! eth1: 10.2.10.18/31 to srl-pe2 e1-3  (ce2=.18, pe2=.19) — VRF-A eBGP
! BGP: AS 65300, eBGP peer pe2 (AS 65200)
frr version 9.0
frr defaults datacenter
hostname frr-ce2
log syslog informational
!
interface lo
 ip address 10.2.0.9/32
!
interface eth1
 description to-srl-pe2-e1-3
 ip address 10.2.10.18/31
 bfd
!
router bgp 65300
 bgp router-id 10.2.0.9
 no bgp ebgp-requires-policy
 !
 neighbor 10.2.10.19 remote-as 65200
 neighbor 10.2.10.19 description pe2-vrf-a
 neighbor 10.2.10.19 bfd
 !
 address-family ipv4 unicast
  network 10.2.0.9/32
  network 172.20.2.0/24
  neighbor 10.2.10.19 activate
 exit-address-family
!
ip route 172.20.2.0/24 Null0
!
bfd
!
