#!/usr/bin/env bash
# D2-T1 (DV1) — event_detection.rs retirement gate.
#
# Runs the 1-hour multi-fault smoke required by the CV7 T4 ADR before
# src/event_detection.rs can be deleted.  If the gate closes, the file is
# deleted and the change is committed and pushed in one operation.
#
# Prerequisites (must be true before running):
#   - cargo build --release is current (run rebuild_and_validate.sh first)
#   - Lab is up with ≥1 BGP session established
#   - bonsai + rules sidecar NOT already running (script starts them)
#
# Usage:
#   bash scripts/ops/event_detection_retirement_gate.sh [--skip-push] [--dry-run]
#
#   --skip-push   Write report + delete file but do not git commit/push.
#   --dry-run     Run the full smoke but skip deletion and push; useful for
#                 a rehearsal without mutating the tree.
#
# Output:
#   docs/test_results/event_detection_retirement_gate_<DATE>.md
#   docs/test_results/event_detection_retirement_gate_<DATE>.logs/
#
# Exit codes:
#   0  gate closed, deletion done (or --dry-run: gate closed, no deletion)
#   1  gate NOT closed (insufficient detections from sidecar)
#   2  pre-flight failure (lab/bonsai/sidecar not healthy)

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BOLD=$'\033[1m'; RESET=$'\033[0m'

# ── Env guard ─────────────────────────────────────────────────────────────────
ENV_DETECTED="$(bash scripts/dev/whichenv.sh 2>/dev/null || echo unknown)"
if [[ "$ENV_DETECTED" == "mac-dev" ]]; then
  echo "${RED}Refused.${RESET} This script is Ubuntu-ops only." >&2
  exit 2
fi

# ── Args ──────────────────────────────────────────────────────────────────────
SKIP_PUSH=0
DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --skip-push) SKIP_PUSH=1 ;;
    --dry-run)   DRY_RUN=1; SKIP_PUSH=1 ;;
    -h|--help)
      sed -n '1,25p' "$0" | sed 's/^# \?//; /^!/d'
      exit 0 ;;
    *) echo "Unknown arg: $arg" >&2; exit 1 ;;
  esac
done

# ── Config ────────────────────────────────────────────────────────────────────
SMOKE_DURATION_SECS=3600        # 1 hour
FAULT_INTERVAL_SECS=180         # inject a fault every 3 minutes
FAULT_HOLD_SECS=20              # keep session down for 20s per injection
DETECTION_WAIT_SECS=40          # time after last fault to let sidecar fire
REQUIRED_RULE_IDS=(bgp_session_down bfd_session_down interface_down)

DATE="$(date -u +%Y%m%dT%H%MZ)"
RESULTS_DIR="$REPO_ROOT/docs/test_results"
REPORT="$RESULTS_DIR/event_detection_retirement_gate_${DATE}.md"
LOG_DIR="$RESULTS_DIR/event_detection_retirement_gate_${DATE}.logs"
mkdir -p "$RESULTS_DIR" "$LOG_DIR"

if [[ -x .venv/bin/python ]]; then PY=.venv/bin/python; else PY=python3; fi

# ── Helpers ───────────────────────────────────────────────────────────────────
log() { echo "$*" | tee -a "$REPORT"; }
hdr() {
  echo
  echo "${BOLD}── $* ──${RESET}"
  { echo; echo "## $*"; echo; } >> "$REPORT"
}

sidecar_metric() {
  local field="$1"
  curl -fsS http://127.0.0.1:3000/api/sidecars 2>/dev/null | $PY -c "
import json,sys
try: d=json.load(sys.stdin)
except: print(0); sys.exit(0)
for s in d.get('sidecars',[]):
    if s.get('kind')=='rules': print(s.get('$field',0)); sys.exit(0)
print(0)" 2>/dev/null || echo 0
}

wait_for_health() {
  local max="${1:-90}" elapsed=0 code
  while (( elapsed < max )); do
    code="$(curl -sS -o /dev/null -w '%{http_code}' http://127.0.0.1:3000/health 2>/dev/null || echo 000)"
    [[ "$code" == "200" || "$code" == "503" ]] && { echo "$code"; return 0; }
    sleep 1; elapsed=$((elapsed+1))
  done
  echo "000"; return 1
}

abort() {
  echo "${RED}ABORT: $*${RESET}" >&2
  log "**ABORT**: $*"
  bash scripts/ops/teardown.sh >/dev/null 2>&1 || true
  exit 2
}

# ── Cleanup on exit ───────────────────────────────────────────────────────────
_cleanup() {
  bash scripts/ops/teardown.sh >/dev/null 2>&1 || true
}
trap _cleanup EXIT

# ── Report header ─────────────────────────────────────────────────────────────
{
  echo "# event_detection.rs Retirement Gate — ${DATE}"
  echo
  echo "Generated by \`scripts/ops/event_detection_retirement_gate.sh\`."
  echo "DRY_RUN=${DRY_RUN}  SKIP_PUSH=${SKIP_PUSH}"
  echo
  echo "**Gate criterion (CV7 T4 ADR)**: Python rules sidecar must be observed"
  echo "catching rule_ids \`bgp_session_down\`, \`bfd_session_down\`, and"
  echo "\`interface_down\` in a live 1-hour smoke, with \`detections_out_total\`"
  echo "counter incrementing on the sidecar (not the Rust fastpath)."
  echo
} > "$REPORT"

# ── Pre-flight: confirm binary exists ─────────────────────────────────────────
hdr "Pre-flight checks"
[[ -x target/release/bonsai ]] || abort "target/release/bonsai not found — run cargo build --release first."
log "- bonsai binary: $(target/release/bonsai --version 2>/dev/null || echo 'ok')"

# Confirm event_detection.rs still exists (idempotency check)
if [[ ! -f src/event_detection.rs ]]; then
  log "**NOTICE**: src/event_detection.rs already deleted. Nothing to do."
  exit 0
fi
log "- src/event_detection.rs: present (will delete on gate close)"

# ── Start bonsai + sidecar ────────────────────────────────────────────────────
hdr "Start bonsai + rules sidecar"
bash scripts/ops/teardown.sh >/dev/null 2>&1 || true
sleep 2

BONSAI_REQUIRE_SIDECAR=rules bash scripts/ops/start_bonsai_with_sidecar.sh \
  >> "$LOG_DIR/startup.log" 2>&1

log "Waiting for /health to respond (up to 90s)…"
HEALTH_CODE="$(wait_for_health 90)" || abort "bonsai /health never responded — see $LOG_DIR/startup.log"
log "- /health responded: HTTP $HEALTH_CODE"

# Wait for sidecar to register and heartbeat
log "Waiting 30s for sidecar registration + first heartbeat…"
sleep 30

SIDECAR_STATUS="$(curl -fsS http://127.0.0.1:3000/api/sidecars 2>/dev/null | \
  $PY -c "
import json,sys
try: d=json.load(sys.stdin)
except: print('no-json'); sys.exit(0)
for s in d.get('sidecars',[]):
    if s.get('kind')=='rules': print(s.get('status','unknown')); sys.exit(0)
print('not-registered')" 2>/dev/null || echo "error")"

log "- rules sidecar status: $SIDECAR_STATUS"
[[ "$SIDECAR_STATUS" == "healthy" ]] || abort "rules sidecar not healthy after 30s (status=$SIDECAR_STATUS) — check logs/bonsai-sidecar.log"

HEALTH_FINAL="$(curl -sS http://127.0.0.1:3000/health 2>/dev/null || true)"
log "- /health body: $HEALTH_FINAL"
echo "$HEALTH_FINAL" | grep -q '"status":"ok"' || abort "/health not ok even with sidecar registered"

# ── Discover fault targets from live graph ─────────────────────────────────────
hdr "Discover fault targets from /api/topology"
TOPO="$(curl -fsS http://127.0.0.1:3000/api/topology 2>/dev/null || true)"
echo "$TOPO" | head -c 500 >> "$REPORT"

# BGP target: first established BGP session
BGP_TARGET="$(echo "$TOPO" | $PY -c "
import json,sys,re
try: d=json.load(sys.stdin)
except: sys.exit(0)
cands=[]
for dev in d.get('devices',[]):
    da=dev.get('address','')
    for n in dev.get('bgp',[]):
        peer=n.get('peer','')
        state=(n.get('state') or '').lower()
        if da and peer and state in ('established','up'): cands.append((da,peer))
for n in d.get('bgp_neighbors',[])+d.get('neighbors',[]):
    da=n.get('device_address') or n.get('device') or ''
    peer=n.get('peer_address') or n.get('peer') or ''
    state=(n.get('session_state') or n.get('state') or '').lower()
    if da and peer and state in ('established','up'): cands.append((da,peer))
if not cands: sys.exit(0)
m=next((c for c in cands if re.search(r'srl|spine|leaf|pe|p\d',c[0],re.I)),None)
dev,peer=m or cands[0]
print(dev,peer)
" 2>/dev/null || true)"

# Interface target: first device with ≥1 interface
IF_TARGET="$(echo "$TOPO" | $PY -c "
import json,sys
try: d=json.load(sys.stdin)
except: sys.exit(0)
for dev in d.get('devices',[]):
    da=dev.get('address','')
    ifaces=dev.get('interfaces',[])
    if da and ifaces:
        iname=ifaces[0].get('name','') if isinstance(ifaces[0],dict) else str(ifaces[0])
        if iname: print(da,iname); sys.exit(0)
" 2>/dev/null || true)"

[[ -n "$BGP_TARGET" ]] || abort "No established BGP session found in /api/topology — lab must be up with converged BGP."
read -r BGP_NODE BGP_PEER <<<"$BGP_TARGET"
log "- BGP fault target:       device=$BGP_NODE  peer=$BGP_PEER"

if [[ -n "$IF_TARGET" ]]; then
  read -r IF_NODE IF_NAME <<<"$IF_TARGET"
  log "- Interface fault target: device=$IF_NODE  interface=$IF_NAME"
else
  log "- Interface fault target: none found — interface_down faults will be skipped"
fi

# BFD target: same node as BGP (BFD sessions typically co-located)
BFD_NODE="$BGP_NODE"
log "- BFD fault target:       device=$BFD_NODE  (same node as BGP)"

# ── 1-hour smoke loop ─────────────────────────────────────────────────────────
hdr "1-hour fault injection smoke (${SMOKE_DURATION_SECS}s)"
log "Started at: $(date -u)"
log "Injecting faults every ${FAULT_INTERVAL_SECS}s for ${SMOKE_DURATION_SECS}s total."
log ""

SMOKE_START="$(date +%s)"
SMOKE_END=$(( SMOKE_START + SMOKE_DURATION_SECS ))

DET_BASELINE="$(sidecar_metric detections_out_total)"
EVT_BASELINE="$(sidecar_metric events_in_total)"
log "Baseline: events_in_total=$EVT_BASELINE  detections_out_total=$DET_BASELINE"
log ""

declare -A RULE_HITS=([bgp_session_down]=0 [bfd_session_down]=0 [interface_down]=0)
FAULT_CYCLE=0

while (( $(date +%s) < SMOKE_END )); do
  FAULT_CYCLE=$(( FAULT_CYCLE + 1 ))
  ELAPSED=$(( $(date +%s) - SMOKE_START ))
  REMAINING=$(( SMOKE_END - $(date +%s) ))
  log "--- Cycle $FAULT_CYCLE  elapsed=${ELAPSED}s  remaining=${REMAINING}s ---"

  # 1. BGP fault
  log "  [bgp] inject bgp-flap $BGP_NODE → $BGP_PEER (hold=${FAULT_HOLD_SECS}s)"
  $PY python/inject_fault.py bgp-flap "$BGP_NODE" "$BGP_PEER" \
    --hold "$FAULT_HOLD_SECS" \
    >> "$LOG_DIR/faults.log" 2>&1 \
    && log "  [bgp] injected ok" \
    || log "  [bgp] inject FAILED (see $LOG_DIR/faults.log)"

  sleep 5

  # 2. BFD fault — srl-leaf1 ethernet-1/1.0 (from chaos plan; bfd-flap needs hostname+subinterface)
  log "  [bfd] inject bfd-flap srl-leaf1 ethernet-1/1.0 (hold=${FAULT_HOLD_SECS}s)"
  $PY python/inject_fault.py bfd-flap srl-leaf1 ethernet-1/1.0 \
    --hold "$FAULT_HOLD_SECS" \
    >> "$LOG_DIR/faults.log" 2>&1 \
    && log "  [bfd] injected ok" \
    || log "  [bfd] inject FAILED (see $LOG_DIR/faults.log) — continuing"

  sleep 5

  # 3. Interface fault — srl-leaf1 ethernet-1/1 (iface-flap, not if-down)
  log "  [iface] inject iface-flap srl-leaf1 ethernet-1/1 (hold=${FAULT_HOLD_SECS}s)"
  $PY python/inject_fault.py iface-flap srl-leaf1 ethernet-1/1 \
    --hold "$FAULT_HOLD_SECS" \
    >> "$LOG_DIR/faults.log" 2>&1 \
    && log "  [iface] injected ok" \
    || log "  [iface] inject FAILED (see $LOG_DIR/faults.log) — continuing"

  # Poll detections for new rule_id hits after each cycle
  sleep "$DETECTION_WAIT_SECS"
  RECENT_RIDS="$(curl -fsS http://127.0.0.1:3000/api/detections 2>/dev/null | $PY -c "
import json,sys
try: d=json.load(sys.stdin)
except: sys.exit(0)
items=d if isinstance(d,list) else d.get('detections',[])
for it in list(items)[-100:]:
    r=it.get('rule_id') or ''
    if r: print(r)
" 2>/dev/null | sort -u || true)"

  DET_NOW="$(sidecar_metric detections_out_total)"
  EVT_NOW="$(sidecar_metric events_in_total)"
  DET_DELTA=$(( DET_NOW - DET_BASELINE ))
  log "  sidecar: events_in=${EVT_NOW}  detections_out=${DET_NOW}  Δdetections=${DET_DELTA}"

  for rid in "${!RULE_HITS[@]}"; do
    if echo "$RECENT_RIDS" | grep -qx "$rid"; then
      RULE_HITS[$rid]=1
      log "  ✓ $rid seen in /api/detections"
    fi
  done

  # Log remaining unseen rule_ids
  UNSEEN=()
  for rid in "${REQUIRED_RULE_IDS[@]}"; do
    [[ "${RULE_HITS[$rid]}" == "0" ]] && UNSEEN+=("$rid")
  done
  [[ ${#UNSEEN[@]} -gt 0 ]] && log "  still waiting for: ${UNSEEN[*]}"

  # Sleep until next fault cycle (minus time already spent above)
  CYCLE_ELAPSED=$(( $(date +%s) - SMOKE_START - (FAULT_CYCLE - 1) * FAULT_INTERVAL_SECS ))
  SLEEP_REMAINING=$(( FAULT_INTERVAL_SECS - CYCLE_ELAPSED - DETECTION_WAIT_SECS - 15 ))
  (( SLEEP_REMAINING > 0 )) && sleep "$SLEEP_REMAINING" || true
done

log ""
log "Smoke complete at: $(date -u)"

# ── Gate evaluation ────────────────────────────────────────────────────────────
hdr "Gate evaluation"

DET_FINAL="$(sidecar_metric detections_out_total)"
EVT_FINAL="$(sidecar_metric events_in_total)"
DET_TOTAL_DELTA=$(( DET_FINAL - DET_BASELINE ))
EVT_TOTAL_DELTA=$(( EVT_FINAL - EVT_BASELINE ))

log "Final sidecar counters:"
log "  events_in_total:      $EVT_FINAL  (Δ +${EVT_TOTAL_DELTA})"
log "  detections_out_total: $DET_FINAL  (Δ +${DET_TOTAL_DELTA})"
log ""
log "Rule_id coverage:"

GATE_CLOSED=1
MISSING_RIDS=()
for rid in "${REQUIRED_RULE_IDS[@]}"; do
  if [[ "${RULE_HITS[$rid]}" == "1" ]]; then
    log "  ✓ $rid — SEEN"
  else
    log "  ✗ $rid — NOT SEEN"
    GATE_CLOSED=0
    MISSING_RIDS+=("$rid")
  fi
done

log ""
if (( DET_TOTAL_DELTA == 0 )); then
  log "**WARNING**: sidecar detections_out_total did not increment (Δ=0)."
  log "Rule_ids may have been written by the Rust fastpath, not the Python sidecar."
  log "Gate requires sidecar counter to tick."
  GATE_CLOSED=0
fi

if (( GATE_CLOSED == 1 )); then
  log "**GATE: CLOSED** — all three rule_ids observed, sidecar counter ticked."
else
  log "**GATE: NOT CLOSED** — missing: ${MISSING_RIDS[*]:-none} / counter_delta=${DET_TOTAL_DELTA}"
fi

# Copy live logs into the report log dir
cp -f logs/bonsai.log         "$LOG_DIR/bonsai.log"         2>/dev/null || true
cp -f logs/bonsai-sidecar.log "$LOG_DIR/bonsai-sidecar.log" 2>/dev/null || true

# ── Teardown ──────────────────────────────────────────────────────────────────
hdr "Teardown"
bash scripts/ops/teardown.sh >> "$LOG_DIR/teardown.log" 2>&1 || true
log "bonsai + sidecar stopped."

# ── Delete event_detection.rs if gate closed ──────────────────────────────────
if (( GATE_CLOSED == 0 )); then
  hdr "Outcome"
  log "Gate not closed. src/event_detection.rs NOT deleted."
  log "Report: $REPORT"
  git add "$REPORT" "$LOG_DIR" 2>/dev/null || true
  git diff --cached --quiet || git commit -m "D2-T1: retirement gate NOT closed ${DATE}" \
    && git push origin main 2>/dev/null || true
  exit 1
fi

if (( DRY_RUN == 1 )); then
  hdr "Outcome (dry-run)"
  log "Gate CLOSED but --dry-run set. Skipping deletion and push."
  log "To complete D2-T1, re-run without --dry-run."
  exit 0
fi

hdr "Delete src/event_detection.rs"

# 1. Remove the file
rm src/event_detection.rs
log "- deleted src/event_detection.rs"

# 2. Remove pub mod declaration from lib.rs
sed -i '/^pub mod event_detection;$/d' src/lib.rs
log "- removed 'pub mod event_detection;' from src/lib.rs"

# 3. Remove event_detection::start() call from server_startup.rs
#    The block is:
#      if let Store::Core(s) = store {
#          bonsai::event_detection::start(std::sync::Arc::clone(s));
#      }
#    Use Python for safe multi-line removal (sed is fragile here).
$PY - <<'PYEOF'
import re, sys

path = "src/server_startup.rs"
with open(path) as f:
    src = f.read()

# Remove the three-line block containing event_detection::start
pattern = r'[ \t]+if let Store::Core\(s\) = store \{\s+bonsai::event_detection::start\([^)]+\);\s+\}\n'
new_src, n = re.subn(pattern, '', src)
if n == 0:
    print("WARNING: event_detection::start block not found — manual removal may be needed", file=sys.stderr)
    sys.exit(0)
with open(path, 'w') as f:
    f.write(new_src)
print(f"removed {n} event_detection::start block(s) from {path}")
PYEOF
log "- removed event_detection::start() call from src/server_startup.rs"

# 4. Verify build
hdr "cargo build --release (post-deletion verification)"
BUILD_LOG="$LOG_DIR/post_deletion_build.log"
if cargo build --release 2>&1 | tee "$BUILD_LOG" | tail -20 | tee -a "$REPORT"; then
  log "**PASS**: cargo build --release succeeded after deletion."
else
  log "**FAIL**: cargo build failed — see $BUILD_LOG"
  log "Manual fix required. Partial commit will NOT be pushed."
  git add "$REPORT" "$LOG_DIR" 2>/dev/null || true
  git diff --cached --quiet || git commit -m "D2-T1: gate closed but build failed post-deletion ${DATE}" \
    >> /dev/null 2>&1
  exit 1
fi

# 5. Commit and push
hdr "Commit and push"
{
  echo
  echo "## Conclusion"
  echo
  echo "Gate closed. src/event_detection.rs deleted. cargo build --release passes."
  echo
  echo "Fault cycles: $FAULT_CYCLE"
  echo "Sidecar detections_out_total delta: +${DET_TOTAL_DELTA}"
  echo "All three retired rule_ids confirmed via Python sidecar."
} >> "$REPORT"

git add src/event_detection.rs src/lib.rs src/server_startup.rs "$REPORT" "$LOG_DIR" 2>/dev/null || true

COMMIT_MSG="D2-T1: delete event_detection.rs — retirement gate closed ${DATE}

Gate evidence: $REPORT
- bgp_session_down:  ${RULE_HITS[bgp_session_down]}  (1=seen)
- bfd_session_down:  ${RULE_HITS[bfd_session_down]}
- interface_down:    ${RULE_HITS[interface_down]}
- sidecar detections_out_total delta: +${DET_TOTAL_DELTA}
- fault cycles: ${FAULT_CYCLE}

Removes:
  src/event_detection.rs (191 lines)
  pub mod event_detection from src/lib.rs
  event_detection::start() call from src/server_startup.rs"

if (( SKIP_PUSH == 1 )); then
  git commit -m "$COMMIT_MSG" >> "$LOG_DIR/git.log" 2>&1 || true
  log "Committed locally. --skip-push set; not pushed."
else
  git commit -m "$COMMIT_MSG" >> "$LOG_DIR/git.log" 2>&1 \
    && git push origin main >> "$LOG_DIR/git.log" 2>&1 \
    && log "Committed and pushed to origin/main." \
    || log "**WARN**: git push failed — commit made locally, push manually."
fi

echo
echo "${GREEN}D2-T1 complete.${RESET}"
echo "Report: $REPORT"
exit 0
