#!/usr/bin/env bash
# CV7 — Comprehensive rebuild + validate driver for the Ubuntu laptop side
# of the Mac→push→Ubuntu→push-results→Mac iteration loop.
#
# Pipeline:
#   1. git pull (warn if dirty)
#   2. regenerate Python protos (so the new RegisterSidecar/SidecarHeartbeat
#      types are available)
#   3. cargo build --release
#   4. cargo test --release sidecar_registry (T4-2 unit tests)
#   5. teardown + start bonsai with sidecar
#   6. probe /api/sidecars before sidecar registers (should be empty)
#   7. wait for sidecar registration + first heartbeat
#   8. probe /api/sidecars after sidecar registers (should have 1 entry)
#   9. probe /health (should be ok with BONSAI_REQUIRE_SIDECAR=rules)
#  10. probe /bonpy/ (should return 200 if SPA built)
#  11. simulate sidecar loss (kill it) + probe /health (should degrade after grace)
#  12. capture all results into docs/test_results/cv7-validation-<date>.md
#  13. git commit + push so Mac sees the results next iteration
#
# Use on Ubuntu laptop only. Refuses on Mac per dev/ops boundary.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BOLD=$'\033[1m'; RESET=$'\033[0m'

ENV_DETECTED="$(bash scripts/dev/whichenv.sh 2>/dev/null || echo unknown)"
if [[ "$ENV_DETECTED" == "mac-dev" ]]; then
  echo "${RED}Refused.${RESET} rebuild_and_validate runs on Ubuntu only." >&2
  exit 2
fi

DATE="$(date -u +%Y-%m-%dT%H%MZ)"
RESULTS_DIR="docs/test_results"
RESULTS_FILE="$RESULTS_DIR/cv7-validation-$DATE.md"
mkdir -p "$RESULTS_DIR"

# Defensive: if the script is interrupted mid-flight (e.g. between step 5
# (start bonsai) and step 11 (teardown)), leave the environment clean for
# the next iteration. The trap runs teardown.sh on any exit path.
_emergency_cleanup() {
  echo "[trap] emergency cleanup — running teardown.sh" >&2
  bash scripts/ops/teardown.sh >/dev/null 2>&1 || true
}
trap _emergency_cleanup EXIT

# All output is mirrored into the results file so Mac sees the same thing
# you see live.
{
  echo "# CV7 validation run — $DATE"
  echo
  echo "Generated by \`scripts/ops/rebuild_and_validate.sh\`."
  echo "Each section below corresponds to one validation step; PASS/FAIL is the line in **bold**."
  echo
} > "$RESULTS_FILE"

PASS_COUNT=0; FAIL_COUNT=0; WARN_COUNT=0

section() {
  local title="$1"
  echo
  echo "${BOLD}── $title ──${RESET}"
  {
    echo
    echo "## $title"
    echo
  } >> "$RESULTS_FILE"
}

record() {
  local status="$1" line="$2"
  echo "$line"
  echo "$line" >> "$RESULTS_FILE"
  case "$status" in
    PASS) PASS_COUNT=$((PASS_COUNT+1)) ;;
    FAIL) FAIL_COUNT=$((FAIL_COUNT+1)) ;;
    WARN) WARN_COUNT=$((WARN_COUNT+1)) ;;
  esac
}

run_or_capture() {
  local cmd="$1"
  echo "    \$ $cmd" >> "$RESULTS_FILE"
  { eval "$cmd" 2>&1 | tee -a "$RESULTS_FILE" ; } || true
}

# ── 1. git pull ───────────────────────────────────────────────────────────────
section "1. git pull origin main"
if [[ -n "$(git status --porcelain)" ]]; then
  record WARN "**WARN**: working tree is dirty; pull may fast-forward but local changes risk loss."
  git status --short | tee -a "$RESULTS_FILE"
fi
run_or_capture "git fetch origin main"
run_or_capture "git reset --hard origin/main"
HEAD_SHA="$(git rev-parse HEAD)"
record PASS "**PASS**: at $HEAD_SHA"

# ── 2. python protos ──────────────────────────────────────────────────────────
section "2. regenerate Python gRPC stubs"
if [[ -x .venv/bin/python ]]; then PY=.venv/bin/python; else PY=python3; fi
if run_or_capture "$PY python/gen_protos.py" ; then
  record PASS "**PASS**: protos regenerated"
else
  record FAIL "**FAIL**: gen_protos.py errored"
fi

# ── 3. cargo build ────────────────────────────────────────────────────────────
section "3. cargo build --release"
if cargo build --release 2>&1 | tail -100 | tee -a "$RESULTS_FILE" ; then
  record PASS "**PASS**: cargo build succeeded"
else
  record FAIL "**FAIL**: cargo build failed — STOP, fix on Mac, re-run iteration"
  echo "Aborting further checks." | tee -a "$RESULTS_FILE"
  exit 1
fi

# ── 4. T4-2 unit tests ────────────────────────────────────────────────────────
section "4. cargo test sidecar_registry (T4-2 unit tests)"
if cargo test --release -p bonsai sidecar_registry 2>&1 | tail -30 | tee -a "$RESULTS_FILE" ; then
  record PASS "**PASS**: sidecar_registry tests pass"
else
  record FAIL "**FAIL**: sidecar_registry tests broken"
fi

# ── 5. teardown + start ───────────────────────────────────────────────────────
section "5. teardown + start bonsai with sidecar"
bash scripts/ops/teardown.sh >> "$RESULTS_FILE" 2>&1 || true
# Start in background; if it errors, the probes will catch it.
bash scripts/ops/start_bonsai_with_sidecar.sh >> "$RESULTS_FILE" 2>&1 &
sleep 8

# ── 6. /api/sidecars after startup ────────────────────────────────────────────
section "6. /api/sidecars after startup"
SIDECARS_JSON="$(curl -fsS http://127.0.0.1:3000/api/sidecars 2>&1 || true)"
echo "$SIDECARS_JSON" >> "$RESULTS_FILE"
N_SIDECARS="$(echo "$SIDECARS_JSON" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(len(d.get("sidecars",[])))' 2>/dev/null || echo 0)"
record PASS "**OBSERVED**: $N_SIDECARS sidecar(s) registered"

# ── 7. wait for first heartbeat ───────────────────────────────────────────────
section "7. wait 20s for first heartbeat then re-probe"
sleep 20
SIDECARS_JSON2="$(curl -fsS http://127.0.0.1:3000/api/sidecars 2>&1 || true)"
echo "$SIDECARS_JSON2" >> "$RESULTS_FILE"
HEALTHY="$(echo "$SIDECARS_JSON2" | python3 -c '
import json,sys
d=json.load(sys.stdin)
print(sum(1 for s in d.get("sidecars",[]) if s.get("status")=="healthy"))
' 2>/dev/null || echo 0)"
if (( HEALTHY >= 1 )); then
  record PASS "**PASS**: $HEALTHY sidecar(s) healthy"
else
  record FAIL "**FAIL**: no sidecars in healthy state"
fi

# ── 8. /health with sidecar present ───────────────────────────────────────────
section "8. /health (BONSAI_REQUIRE_SIDECAR=rules already set)"
HEALTH_JSON="$(curl -fsS http://127.0.0.1:3000/health 2>&1 || true)"
echo "$HEALTH_JSON" >> "$RESULTS_FILE"
if echo "$HEALTH_JSON" | grep -q '"status":"ok"'; then
  record PASS "**PASS**: /health = ok"
else
  record FAIL "**FAIL**: /health did not return ok with sidecar registered"
fi

# ── 9. bonpy UI ───────────────────────────────────────────────────────────────
section "9. bonpy UI served at /bonpy/"
if curl -fsS -o /dev/null http://127.0.0.1:3000/bonpy/ 2>&1 ; then
  record PASS "**PASS**: GET /bonpy/ returned 200"
else
  record WARN "**WARN**: /bonpy/ not reachable — ensure 'cd ui-bonpy && npm install && npm run build' ran"
fi

# ── 10. degrade probe ─────────────────────────────────────────────────────────
section "10. degrade probe (kill sidecar; /health should flip to degraded after stale window)"
if [[ -f runtime/bonsai-sidecar.pid ]]; then
  SID_PID="$(cat runtime/bonsai-sidecar.pid)"
  kill "$SID_PID" 2>/dev/null || true
  echo "killed sidecar pid $SID_PID — waiting 130s for lost-status window" >> "$RESULTS_FILE"
  sleep 130
  HEALTH_AFTER="$(curl -sS -o /dev/null -w '%{http_code}' http://127.0.0.1:3000/health || echo 000)"
  HEALTH_BODY="$(curl -sS http://127.0.0.1:3000/health || true)"
  echo "HTTP $HEALTH_AFTER  body: $HEALTH_BODY" >> "$RESULTS_FILE"
  if [[ "$HEALTH_AFTER" == "503" ]] && echo "$HEALTH_BODY" | grep -q '"status":"degraded"'; then
    record PASS "**PASS**: /health correctly degraded after sidecar loss"
  else
    record WARN "**WARN**: expected 503 degraded, got $HEALTH_AFTER (timing may need tuning)"
  fi
else
  record WARN "**WARN**: no sidecar pid file — degrade probe skipped"
fi

# ── 11. teardown ──────────────────────────────────────────────────────────────
section "11. teardown"
bash scripts/ops/teardown.sh >> "$RESULTS_FILE" 2>&1 || true
record PASS "**PASS**: teardown clean"

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "${BOLD}── Summary ──${RESET}"
echo "  PASS: $PASS_COUNT"
echo "  WARN: $WARN_COUNT"
echo "  FAIL: $FAIL_COUNT"
{
  echo
  echo "## Summary"
  echo
  echo "- PASS: $PASS_COUNT"
  echo "- WARN: $WARN_COUNT"
  echo "- FAIL: $FAIL_COUNT"
  echo
  if (( FAIL_COUNT == 0 )); then
    echo "**Verdict**: T4-1 through T4-6 validated. Tier 4 is safe to close pending T4-7 (delete src/event_detection.rs)."
  else
    echo "**Verdict**: failures present. Mac side should address before iterating."
  fi
} >> "$RESULTS_FILE"

# ── Push results back to repo so Mac sees them ────────────────────────────────
section "12. push results"
git add "$RESULTS_FILE"
if git diff --cached --quiet; then
  echo "no changes to commit" | tee -a "$RESULTS_FILE"
else
  git commit -m "validation: cv7 $DATE — PASS=$PASS_COUNT WARN=$WARN_COUNT FAIL=$FAIL_COUNT" >> "$RESULTS_FILE" 2>&1 || true
  git push origin main >> "$RESULTS_FILE" 2>&1 || record WARN "**WARN**: git push failed — commit was made but not pushed"
fi

echo
echo "Results written to: $RESULTS_FILE"

(( FAIL_COUNT == 0 )) && exit 0 || exit 1
