#!/usr/bin/env bash
# CV7 — Comprehensive rebuild + validate driver for the Ubuntu laptop side
# of the Mac→push→Ubuntu→push-results→Mac iteration loop.
#
# Pipeline:
#   1. git pull (warn ONLY if non-results files are dirty)
#   2. regenerate Python protos
#   3. bonpy SPA build (npm install + build under ui-bonpy/)
#   4. cargo build --release (full stderr captured)
#   5. cargo test --release sidecar_registry (T4-2 unit tests)
#   6. teardown + start bonsai with sidecar
#   7. probe /api/sidecars after startup (sidecar registers)
#   8. wait 20s + re-probe (heartbeat ticked)
#   9. probe /health (should be ok with BONSAI_REQUIRE_SIDECAR=rules)
#  10. probe /bonpy/ (should return 200 since step 3 built it)
#  11. T4-7 GATE: inject one real BGP flap + verify Python sidecar fires
#      `bgp_session_*` detection; assert detections_out_total tick > 0.
#      If no lab BGP neighbours are reachable, recorded as WARN (not FAIL).
#  12. degrade probe (kill sidecar; /health flips to degraded after stale window)
#  13. teardown
#  14. push results to origin/main so Mac sees them next iteration
#
# Comprehensive error capture: every command's full stdout+stderr is mirrored
# into the results .md file AND (for cargo build/test) into a sibling
# .log file referenced from the results. On any FAIL the relevant log
# locations are listed so Mac can pull and inspect.
#
# Use on Ubuntu laptop only. Refuses on Mac per dev/ops boundary.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BOLD=$'\033[1m'; RESET=$'\033[0m'

ENV_DETECTED="$(bash scripts/dev/whichenv.sh 2>/dev/null || echo unknown)"
if [[ "$ENV_DETECTED" == "mac-dev" ]]; then
  echo "${RED}Refused.${RESET} rebuild_and_validate runs on Ubuntu only." >&2
  exit 2
fi

DATE="$(date -u +%Y-%m-%dT%H%MZ)"
RESULTS_DIR="docs/test_results"
RESULTS_FILE="$RESULTS_DIR/cv7-validation-$DATE.md"
LOG_DIR="$RESULTS_DIR/cv7-validation-$DATE.logs"
mkdir -p "$RESULTS_DIR" "$LOG_DIR"

# Defensive: if the script is interrupted mid-flight (e.g. between step 6
# (start bonsai) and step 13 (teardown)), leave the environment clean for
# the next iteration. The trap runs teardown.sh on any exit path.
_emergency_cleanup() {
  echo "[trap] emergency cleanup — running teardown.sh" >&2
  bash scripts/ops/teardown.sh >/dev/null 2>&1 || true
}
trap _emergency_cleanup EXIT

# All output is mirrored into the results file so Mac sees the same thing
# you see live.
{
  echo "# CV7 validation run — $DATE"
  echo
  echo "Generated by \`scripts/ops/rebuild_and_validate.sh\`."
  echo "Each section corresponds to one validation step; PASS/FAIL/WARN is the line in **bold**."
  echo
  echo "Side-channel logs (cargo build/test, npm build, bonsai+sidecar stdout):"
  echo "  \`$LOG_DIR/\`"
  echo
} > "$RESULTS_FILE"

PASS_COUNT=0; FAIL_COUNT=0; WARN_COUNT=0

section() {
  local title="$1"
  echo
  echo "${BOLD}── $title ──${RESET}"
  {
    echo
    echo "## $title"
    echo
  } >> "$RESULTS_FILE"
}

record() {
  local status="$1" line="$2"
  echo "$line"
  echo "$line" >> "$RESULTS_FILE"
  case "$status" in
    PASS) PASS_COUNT=$((PASS_COUNT+1)) ;;
    FAIL) FAIL_COUNT=$((FAIL_COUNT+1)) ;;
    WARN) WARN_COUNT=$((WARN_COUNT+1)) ;;
  esac
}

# Run a shell command, mirror stdout+stderr into the results file, also write
# a copy into $LOG_DIR/<tag>.log. Returns the command's exit code.
run_or_capture_to_log() {
  local tag="$1" cmd="$2"
  local logfile="$LOG_DIR/$tag.log"
  echo "    \$ $cmd" >> "$RESULTS_FILE"
  echo "    (full log: $logfile)" >> "$RESULTS_FILE"
  echo "    \$ $cmd" > "$logfile"
  { eval "$cmd" 2>&1 | tee -a "$logfile" | tee -a "$RESULTS_FILE" ; }
  return ${PIPESTATUS[0]}
}

# Read a numeric field from /api/sidecars for the first sidecar of kind=rules.
sidecar_counter() {
  local field="$1"
  curl -fsS http://127.0.0.1:3000/api/sidecars 2>/dev/null | python3 -c "
import json,sys
try:
    d = json.load(sys.stdin)
except Exception:
    print(0); sys.exit(0)
for s in d.get('sidecars', []):
    if s.get('kind') == 'rules':
        print(s.get('$field', 0)); sys.exit(0)
print(0)
" 2>/dev/null || echo 0
}

# ── 1. git pull ───────────────────────────────────────────────────────────────
section "1. git pull origin main"
# Cosmetic-WARN fix: only flag if files OUTSIDE docs/test_results/ are dirty.
# The script's own about-to-be-created results file always shows up as dirty;
# don't count it.
DIRTY_NON_RESULTS="$(git status --porcelain | awk '$2 !~ /^docs\/test_results\// {print}')"
if [[ -n "$DIRTY_NON_RESULTS" ]]; then
  record WARN "**WARN**: working tree is dirty in non-results files; pull may overwrite local changes."
  echo "$DIRTY_NON_RESULTS" | tee -a "$RESULTS_FILE"
fi
run_or_capture_to_log "01-git-fetch"  "git fetch origin main"
run_or_capture_to_log "01-git-reset"  "git reset --hard origin/main"
HEAD_SHA="$(git rev-parse HEAD)"
record PASS "**PASS**: at $HEAD_SHA"

# ── 2. python protos ──────────────────────────────────────────────────────────
section "2. regenerate Python gRPC stubs"
if [[ -x .venv/bin/python ]]; then PY=.venv/bin/python; else PY=python3; fi
if run_or_capture_to_log "02-gen-protos" "$PY python/gen_protos.py" ; then
  record PASS "**PASS**: protos regenerated"
else
  record FAIL "**FAIL**: gen_protos.py errored — see $LOG_DIR/02-gen-protos.log"
fi

# ── 3. bonpy SPA build ────────────────────────────────────────────────────────
section "3. bonpy SPA build (ui-bonpy/)"
if [[ ! -d ui-bonpy ]]; then
  record WARN "**WARN**: ui-bonpy/ directory missing — bonpy SPA scaffold not present."
elif ! command -v npm >/dev/null 2>&1; then
  record WARN "**WARN**: npm not on PATH — bonpy SPA cannot be built. Install Node.js."
else
  pushd ui-bonpy >/dev/null
  if [[ ! -d node_modules ]]; then
    if ! run_or_capture_to_log "03-bonpy-npm-install" "npm install --no-audit --no-fund --silent"; then
      popd >/dev/null
      record FAIL "**FAIL**: npm install failed — see $LOG_DIR/03-bonpy-npm-install.log"
      bash scripts/ops/teardown.sh >/dev/null 2>&1 || true
      continue 2>/dev/null || true
    fi
  fi
  if run_or_capture_to_log "03-bonpy-build" "npm run build"; then
    record PASS "**PASS**: bonpy SPA built — ui-bonpy/dist/ ready for Axum to serve at /bonpy/."
  else
    record FAIL "**FAIL**: npm run build failed — see $LOG_DIR/03-bonpy-build.log"
  fi
  popd >/dev/null
fi

# ── 4. cargo build ────────────────────────────────────────────────────────────
section "4. cargo build --release"
# Full stderr captured to side-log. Results-file gets the tail (last 100 lines)
# so the .md stays readable, but the operator can `cat` the full log on FAIL.
CARGO_LOG="$LOG_DIR/04-cargo-build.log"
echo "    \$ cargo build --release" >> "$RESULTS_FILE"
echo "    (full log: $CARGO_LOG)" >> "$RESULTS_FILE"
if cargo build --release 2>&1 | tee "$CARGO_LOG" | tail -100 | tee -a "$RESULTS_FILE" ; then
  record PASS "**PASS**: cargo build succeeded"
else
  record FAIL "**FAIL**: cargo build failed — STOP, fix on Mac, re-run iteration. Full log: $CARGO_LOG"
  echo "Aborting further checks." | tee -a "$RESULTS_FILE"
  exit 1
fi

# ── 5. T4-2 unit tests ────────────────────────────────────────────────────────
section "5. cargo test sidecar_registry (T4-2 unit tests)"
TEST_LOG="$LOG_DIR/05-cargo-test.log"
echo "    \$ cargo test --release -p bonsai sidecar_registry" >> "$RESULTS_FILE"
echo "    (full log: $TEST_LOG)" >> "$RESULTS_FILE"
if cargo test --release -p bonsai sidecar_registry 2>&1 | tee "$TEST_LOG" | tail -40 | tee -a "$RESULTS_FILE" ; then
  record PASS "**PASS**: sidecar_registry tests pass"
else
  record FAIL "**FAIL**: sidecar_registry tests broken — full log: $TEST_LOG"
fi

# ── 6. teardown + start ───────────────────────────────────────────────────────
section "6. teardown + start bonsai with sidecar"
bash scripts/ops/teardown.sh >> "$RESULTS_FILE" 2>&1 || true
# Start in background; if it errors, the probes will catch it. The wrapper
# itself writes to logs/bonsai.log and logs/bonsai-sidecar.log — we copy
# those into the side-log dir below for the Mac-side iteration.
bash scripts/ops/start_bonsai_with_sidecar.sh >> "$RESULTS_FILE" 2>&1 &
sleep 8

# ── 7. /api/sidecars after startup ────────────────────────────────────────────
section "7. /api/sidecars after startup"
SIDECARS_JSON="$(curl -fsS http://127.0.0.1:3000/api/sidecars 2>&1 || true)"
echo "$SIDECARS_JSON" >> "$RESULTS_FILE"
N_SIDECARS="$(echo "$SIDECARS_JSON" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(len(d.get("sidecars",[])))' 2>/dev/null || echo 0)"
if (( N_SIDECARS >= 1 )); then
  record PASS "**PASS**: $N_SIDECARS sidecar(s) registered"
else
  record FAIL "**FAIL**: no sidecars registered — check logs/bonsai-sidecar.log"
  cp -f logs/bonsai-sidecar.log "$LOG_DIR/06-sidecar.log" 2>/dev/null || true
fi

# ── 8. wait for first heartbeat ───────────────────────────────────────────────
section "8. wait 20s for first heartbeat then re-probe"
sleep 20
SIDECARS_JSON2="$(curl -fsS http://127.0.0.1:3000/api/sidecars 2>&1 || true)"
echo "$SIDECARS_JSON2" >> "$RESULTS_FILE"
HEALTHY="$(echo "$SIDECARS_JSON2" | python3 -c '
import json,sys
d=json.load(sys.stdin)
print(sum(1 for s in d.get("sidecars",[]) if s.get("status")=="healthy"))
' 2>/dev/null || echo 0)"
if (( HEALTHY >= 1 )); then
  record PASS "**PASS**: $HEALTHY sidecar(s) healthy"
else
  record FAIL "**FAIL**: no sidecars in healthy state"
fi

# ── 9. /health with sidecar present ───────────────────────────────────────────
section "9. /health (BONSAI_REQUIRE_SIDECAR=rules already set)"
HEALTH_JSON="$(curl -fsS http://127.0.0.1:3000/health 2>&1 || true)"
echo "$HEALTH_JSON" >> "$RESULTS_FILE"
if echo "$HEALTH_JSON" | grep -q '"status":"ok"'; then
  record PASS "**PASS**: /health = ok"
else
  record FAIL "**FAIL**: /health did not return ok with sidecar registered"
fi

# ── 10. bonpy UI ──────────────────────────────────────────────────────────────
section "10. bonpy UI served at /bonpy/"
BONPY_CODE="$(curl -sS -o /dev/null -w '%{http_code}' http://127.0.0.1:3000/bonpy/ || echo 000)"
echo "HTTP $BONPY_CODE  /bonpy/" >> "$RESULTS_FILE"
if [[ "$BONPY_CODE" == "200" ]]; then
  record PASS "**PASS**: GET /bonpy/ returned 200"
else
  record WARN "**WARN**: /bonpy/ returned $BONPY_CODE — step 3 may have failed; see $LOG_DIR/03-bonpy-build.log"
fi

# ── 11. T4-7 gate: fault injection round-trip ─────────────────────────────────
# Proves the Python sidecar catches the three rule_ids the Rust fastpath
# currently double-handles. If this passes, src/event_detection.rs is safe
# to delete in the next Mac iteration.
section "11. T4-7 gate: fault injection round-trip"

# 11a. Pick an established BGP target from /api/topology (or skip with WARN).
BGP_TARGET="$(curl -fsS http://127.0.0.1:3000/api/topology 2>/dev/null | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
# Schema varies across releases; try common shapes.
candidates = []
for n in d.get('bgp_neighbors', []) + d.get('neighbors', []) + d.get('bgp', []):
    dev = n.get('device_address') or n.get('device') or n.get('source')
    peer = n.get('peer_address') or n.get('peer')
    state = (n.get('session_state') or n.get('state') or '').lower()
    if dev and peer and state in ('established', 'up'):
        candidates.append((dev, peer))
if not candidates:
    sys.exit(0)
# Prefer one whose hostname matches a known clab pattern (so inject_fault has
# a chance of resolving credentials via bonsai.toml). Otherwise take the first.
import re
clab_match = next((c for c in candidates if re.search(r'srl|spine|leaf|pe|p1|p2', c[0], re.I)), None)
dev, peer = clab_match or candidates[0]
print(dev, peer)
" 2>/dev/null || true)"

if [[ -z "$BGP_TARGET" ]]; then
  record WARN "**WARN**: no established BGP neighbour found in /api/topology — T4-7 gate cannot be closed from this iteration. Start a lab (\`bash scripts/lab/redeploy_dc.sh\`) and re-run."
else
  read -r NODE PEER <<<"$BGP_TARGET"
  echo "selected fault target: device=$NODE peer=$PEER" >> "$RESULTS_FILE"

  DET_BEFORE="$(sidecar_counter detections_out_total)"
  EVT_BEFORE="$(sidecar_counter events_in_total)"
  echo "before: events_in_total=$EVT_BEFORE detections_out_total=$DET_BEFORE" >> "$RESULTS_FILE"

  # Map device-address back to a node hostname inject_fault.py understands.
  # bonsai.toml's [[target]] blocks key by address; inject_fault accepts both
  # the address and the clab node name. We pass the address — inject_fault
  # resolves vendor from bonsai.toml.
  INJ_LOG="$LOG_DIR/11-inject_fault.log"
  echo "    \$ $PY python/inject_fault.py bgp-flap $NODE $PEER --hold 10" >> "$RESULTS_FILE"
  echo "    (full log: $INJ_LOG)" >> "$RESULTS_FILE"
  if $PY python/inject_fault.py bgp-flap "$NODE" "$PEER" --hold 10 > "$INJ_LOG" 2>&1; then
    cat "$INJ_LOG" | tail -30 >> "$RESULTS_FILE"
    # The bgp-flap holds for 10s before restore; the rule evaluator needs a
    # few more seconds to fire and persist. Generous wait so we don't race.
    echo "waiting 25s for sidecar to fire and persist detection…" >> "$RESULTS_FILE"
    sleep 25

    DET_AFTER="$(sidecar_counter detections_out_total)"
    EVT_AFTER="$(sidecar_counter events_in_total)"
    DET_DELTA=$((DET_AFTER - DET_BEFORE))
    EVT_DELTA=$((EVT_AFTER - EVT_BEFORE))
    echo "after:  events_in_total=$EVT_AFTER detections_out_total=$DET_AFTER  (Δevt=$EVT_DELTA Δdet=$DET_DELTA)" >> "$RESULTS_FILE"

    # Inspect /api/detections for recent BGP-flap-flavoured rule_ids.
    RECENT_RIDS="$(curl -fsS http://127.0.0.1:3000/api/detections 2>/dev/null | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
items = d if isinstance(d, list) else d.get('detections', [])
# Look only at the most recent 50; we just flapped one peer.
for it in list(items)[-50:]:
    rid = it.get('rule_id') or ''
    if rid:
        print(rid)
" 2>/dev/null | sort -u)"
    echo "recent rule_ids in /api/detections:" >> "$RESULTS_FILE"
    echo "$RECENT_RIDS" >> "$RESULTS_FILE"

    HIT_RETIRED=0
    for rid in bgp_session_down bgp_session_flap interface_down bfd_session_down; do
      if echo "$RECENT_RIDS" | grep -qx "$rid"; then
        HIT_RETIRED=1
        echo "  ✓ saw retired-fastpath rule_id $rid" >> "$RESULTS_FILE"
      fi
    done

    if (( DET_DELTA > 0 )) && (( HIT_RETIRED == 1 )); then
      record PASS "**PASS**: Python sidecar fired retired-fastpath rule_id AND counter ticked (Δdet=$DET_DELTA). T4-7 gate closeable."
    elif (( HIT_RETIRED == 1 )); then
      record WARN "**WARN**: retired-fastpath rule_id appeared in /api/detections but sidecar counter Δ=0 — could be Rust fastpath writing, not Python. Cannot close T4-7 gate from this iteration."
    elif (( DET_DELTA > 0 )); then
      record WARN "**WARN**: sidecar counter ticked (Δdet=$DET_DELTA) but no retired-fastpath rule_id seen — Python is firing OTHER rules; gate inconclusive for the 3 retired ids."
    else
      record WARN "**WARN**: fault injected but neither counter nor /api/detections shows new bgp_* detections. Check inject_fault output + logs/bonsai.log."
    fi
  else
    cat "$INJ_LOG" | tail -50 >> "$RESULTS_FILE"
    record WARN "**WARN**: inject_fault.py failed — likely lab/credential issue. Full log: $INJ_LOG"
  fi
fi

# ── 12. degrade probe ─────────────────────────────────────────────────────────
section "12. degrade probe (kill sidecar; /health should flip to degraded after stale window)"
if [[ -f runtime/bonsai-sidecar.pid ]]; then
  SID_PID="$(cat runtime/bonsai-sidecar.pid)"
  kill "$SID_PID" 2>/dev/null || true
  echo "killed sidecar pid $SID_PID — waiting 130s for lost-status window" >> "$RESULTS_FILE"
  sleep 130
  HEALTH_AFTER="$(curl -sS -o /dev/null -w '%{http_code}' http://127.0.0.1:3000/health || echo 000)"
  HEALTH_BODY="$(curl -sS http://127.0.0.1:3000/health || true)"
  echo "HTTP $HEALTH_AFTER  body: $HEALTH_BODY" >> "$RESULTS_FILE"
  if [[ "$HEALTH_AFTER" == "503" ]] && echo "$HEALTH_BODY" | grep -q '"status":"degraded"'; then
    record PASS "**PASS**: /health correctly degraded after sidecar loss"
  else
    record WARN "**WARN**: expected 503 degraded, got $HEALTH_AFTER (timing may need tuning)"
  fi
else
  record WARN "**WARN**: no sidecar pid file — degrade probe skipped"
fi

# ── 13. teardown ──────────────────────────────────────────────────────────────
section "13. teardown"
bash scripts/ops/teardown.sh >> "$RESULTS_FILE" 2>&1 || true
# Copy bonsai + sidecar live logs into the side-log directory so the Mac
# iteration can see them even if the lab gets torn down later.
cp -f logs/bonsai.log         "$LOG_DIR/13-bonsai.log"         2>/dev/null || true
cp -f logs/bonsai-sidecar.log "$LOG_DIR/13-bonsai-sidecar.log" 2>/dev/null || true
record PASS "**PASS**: teardown clean; live logs copied to $LOG_DIR/"

# ── Summary ───────────────────────────────────────────────────────────────────
echo
echo "${BOLD}── Summary ──${RESET}"
echo "  PASS: $PASS_COUNT"
echo "  WARN: $WARN_COUNT"
echo "  FAIL: $FAIL_COUNT"
{
  echo
  echo "## Summary"
  echo
  echo "- PASS: $PASS_COUNT"
  echo "- WARN: $WARN_COUNT"
  echo "- FAIL: $FAIL_COUNT"
  echo
  if (( FAIL_COUNT == 0 )); then
    if (( WARN_COUNT == 0 )); then
      echo "**Verdict**: T4-1 through T4-7 gate closed. Tier 4 ready to land deletion of src/event_detection.rs in next Mac iteration."
    else
      echo "**Verdict**: T4-1 through T4-6 validated. WARNs above (often: no lab BGP neighbour reachable for T4-7 gate) need attention before deleting src/event_detection.rs."
    fi
  else
    echo "**Verdict**: failures present. Mac side must address before iterating. Side-channel logs in \`$LOG_DIR/\`."
  fi
  echo
  echo "## Side-channel logs (full stdout+stderr for each command)"
  echo
  echo '```'
  ls -la "$LOG_DIR" 2>/dev/null | sed -n '2,$p'
  echo '```'
} >> "$RESULTS_FILE"

# ── Push results back to repo so Mac sees them ────────────────────────────────
section "14. push results"
git add "$RESULTS_FILE" "$LOG_DIR" 2>/dev/null || true
if git diff --cached --quiet; then
  echo "no changes to commit" | tee -a "$RESULTS_FILE"
else
  git commit -m "validation: cv7 $DATE — PASS=$PASS_COUNT WARN=$WARN_COUNT FAIL=$FAIL_COUNT" >> "$RESULTS_FILE" 2>&1 || true
  git push origin main >> "$RESULTS_FILE" 2>&1 || record WARN "**WARN**: git push failed — commit was made but not pushed"
fi

echo
echo "Results written to: $RESULTS_FILE"
echo "Side-channel logs in: $LOG_DIR/"

(( FAIL_COUNT == 0 )) && exit 0 || exit 1
