! frr-ce1 — SP lab Customer Edge (FRR 9.x)
! Loopback: 10.2.0.8/32
! eth1: 10.2.10.16/31 to srl-pe1 e1-3  (ce1=.16, pe1=.17) — VRF-A eBGP
! BGP: AS 65300, eBGP peer pe1 (AS 65200)
frr version 9.0
frr defaults datacenter
hostname frr-ce1
log syslog informational
!
interface lo
 ip address 10.2.0.8/32
!
interface eth1
 description to-srl-pe1-e1-3
 ip address 10.2.10.16/31
 bfd
!
router bgp 65300
 bgp router-id 10.2.0.8
 no bgp ebgp-requires-policy
 !
 neighbor 10.2.10.17 remote-as 65200
 neighbor 10.2.10.17 description pe1-vrf-a
 neighbor 10.2.10.17 bfd
 !
 address-family ipv4 unicast
  network 10.2.0.8/32
  network 172.20.1.0/24
  neighbor 10.2.10.17 activate
 exit-address-family
!
ip route 172.20.1.0/24 Null0
!
bfd
!
