#!/usr/bin/env bash
# deploy-p4.sh — Phase 4 lab (3× SRL + 1× XRd, 172.100.102.x)
#
# Usage (from WSL, must be run as root or with sudo):
#   bash /mnt/c/Users/arjun/Desktop/bonsai/lab/fast-iteration/deploy-p4.sh [deploy|destroy|reconfigure]
#
#   deploy       — bring up bonsai-p4 (clab deploy)
#   destroy      — tear down bonsai-p4 and the old bonsai-mv lab if present
#   reconfigure  — destroy + deploy (fresh node config apply)
#
# After deploy, update bonsai.toml on Windows:
#   - Copy the printed CA cert path into ca_cert fields
#   - Confirm the 172.100.102.0/24 route is present on Windows

set -euo pipefail

ACTION=${1:-deploy}
SRC="/mnt/c/Users/arjun/Desktop/bonsai/lab/fast-iteration"
LAB_P4="/home/${SUDO_USER:-$USER}/bonsai-labs/phase4"
LAB_MV="/home/${SUDO_USER:-$USER}/bonsai-labs/multivendor"
TOML_WIN="/mnt/c/Users/arjun/Desktop/bonsai/bonsai.toml"

# ── helpers ───────────────────────────────────────────────────────────────────

add_route() {
  WSL_IP=$(ip addr show eth0 2>/dev/null | awk '/inet / {split($2,a,"/"); print a[1]; exit}')
  if [ -z "$WSL_IP" ]; then
    echo "WARN: could not detect WSL eth0 IP — add route manually:"
    echo "  route add 172.100.102.0 mask 255.255.255.0 <WSL_IP>"
    return
  fi
  echo "Adding Windows route 172.100.102.0/24 via WSL ($WSL_IP) ..."
  powershell.exe -Command "route add 172.100.102.0 mask 255.255.255.0 $WSL_IP" 2>/dev/null \
    && echo "  Route added." \
    || echo "  NOTE: run in admin PowerShell: route add 172.100.102.0 mask 255.255.255.0 $WSL_IP"
}

destroy_old_mv() {
  if [ -d "$LAB_MV" ]; then
    echo "Destroying old multivendor lab (bonsai-mv) ..."
    cd "$LAB_MV"
    sudo clab destroy -t multivendor.clab.yml --cleanup 2>/dev/null || true
    echo "  Done."
  fi
}

# ── actions ───────────────────────────────────────────────────────────────────

do_destroy() {
  destroy_old_mv

  if [ -d "$LAB_P4" ]; then
    echo "Destroying bonsai-p4 lab ..."
    cd "$LAB_P4"
    sudo clab destroy -t bonsai-phase4.clab.yml --cleanup 2>/dev/null || true
    echo "  Done."
  else
    echo "Lab dir $LAB_P4 not found — nothing to destroy."
  fi
}

do_deploy() {
  destroy_old_mv

  echo "Syncing lab files to $LAB_P4 ..."
  mkdir -p "$LAB_P4"
  rsync -a --exclude='clab-*' "$SRC/" "$LAB_P4/"

  cd "$LAB_P4"
  echo "Deploying bonsai-p4 ..."
  sudo clab deploy -t bonsai-phase4.clab.yml

  # Extract SRL CA cert (generated by clab per-lab)
  CA_SRC="$LAB_P4/clab-bonsai-p4/.tls/ca/ca.pem"
  CA_DST="$SRC/p4-ca.pem"
  if [ -f "$CA_SRC" ]; then
    cp "$CA_SRC" "$CA_DST"
    echo "CA cert copied to $CA_DST"
  else
    echo "WARN: CA cert not found at $CA_SRC — check clab output above"
    CA_DST="<NOT FOUND>"
  fi

  add_route

  echo ""
  echo "================================================================"
  echo "  bonsai-p4 is up — update bonsai.toml on Windows:"
  echo "================================================================"
  echo ""
  echo "graph_path = \"bonsai.db\""
  echo ""
  echo "[[target]]"
  echo "address    = \"172.100.102.11:57400\""
  echo "hostname   = \"srl-spine1\""
  echo "tls_domain = \"clab-bonsai-p4-srl-spine1\""
  echo "ca_cert    = \"lab/fast-iteration/p4-ca.pem\""
  echo "username   = \"admin\""
  echo "password   = \"NokiaSrl1!\""
  echo ""
  echo "[[target]]"
  echo "address    = \"172.100.102.12:57400\""
  echo "hostname   = \"srl-leaf1\""
  echo "tls_domain = \"clab-bonsai-p4-srl-leaf1\""
  echo "ca_cert    = \"lab/fast-iteration/p4-ca.pem\""
  echo "username   = \"admin\""
  echo "password   = \"NokiaSrl1!\""
  echo ""
  echo "[[target]]"
  echo "address    = \"172.100.102.13:57400\""
  echo "hostname   = \"srl-leaf2\""
  echo "tls_domain = \"clab-bonsai-p4-srl-leaf2\""
  echo "ca_cert    = \"lab/fast-iteration/p4-ca.pem\""
  echo "username   = \"admin\""
  echo "password   = \"NokiaSrl1!\""
  echo ""
  echo "[[target]]"
  echo "address  = \"172.100.102.21:57400\""
  echo "hostname = \"xrd-pe1\""
  echo "username = \"cisco\""
  echo "password = \"cisco123!\""
  echo ""
  echo "================================================================"
  echo ""
  echo "SSH access (XRd needs ~5 min after boot):"
  echo "  ssh admin@172.100.102.11    # srl-spine1  pass: NokiaSrl1!"
  echo "  ssh admin@172.100.102.12    # srl-leaf1   pass: NokiaSrl1!"
  echo "  ssh admin@172.100.102.13    # srl-leaf2   pass: NokiaSrl1!"
  echo "  ssh cisco@172.100.102.21    # xrd-pe1     pass: cisco123!"
  echo ""
  echo "Fault injection examples:"
  echo "  clab tools netem set bonsai-p4 srl-spine1 e1-1 --delay 500ms  # BGP flap on spine-leaf1 link"
  echo "  clab tools netem set bonsai-p4 srl-spine1 e1-1 --delay 0ms    # Restore"
  echo "  ssh admin@172.100.102.11 'sr_cli \"set / interface ethernet-1/1 admin-state disable\"'"
}

# ── main ──────────────────────────────────────────────────────────────────────

case "$ACTION" in
  deploy)
    do_deploy
    ;;
  destroy)
    do_destroy
    ;;
  reconfigure)
    do_destroy
    do_deploy
    ;;
  *)
    echo "Usage: $0 [deploy|destroy|reconfigure]"
    exit 1
    ;;
esac
