#!/usr/bin/env bash
# deploy-p4.sh — Phase 4 lab (3× SRL + 1× XRd, 172.100.102.x)
#
# Usage (native Linux, run as root or with sudo):
#   sudo bash lab/fast-iteration/deploy-p4.sh [deploy|destroy|reconfigure]
#
#   deploy       — bring up bonsai-p4 (clab deploy)
#   destroy      — tear down bonsai-p4
#   reconfigure  — destroy + deploy (fresh node config apply)

set -euo pipefail

ACTION=${1:-deploy}
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── actions ───────────────────────────────────────────────────────────────────

do_destroy() {
  echo "Destroying bonsai-p4 lab ..."
  cd "$DIR"
  sudo clab destroy -t bonsai-phase4.clab.yml --cleanup 2>/dev/null || true
  echo "  Done."
}

do_deploy() {
  echo "Deploying bonsai-p4 ..."
  cd "$DIR"
  sudo clab deploy -t bonsai-phase4.clab.yml

  # Extract SRL CA cert (generated by clab per-lab)
  CA_SRC="$DIR/clab-bonsai-p4/.tls/ca/ca.pem"
  CA_DST="$DIR/p4-ca.pem"
  if [ -f "$CA_SRC" ]; then
    cp "$CA_SRC" "$CA_DST"
    echo "CA cert copied to $CA_DST"
  else
    echo "WARN: CA cert not found at $CA_SRC — check clab output above"
    CA_DST="<NOT FOUND>"
  fi

  echo ""
  echo "================================================================"
  echo "  bonsai-p4 is up — native Linux deploy"
  echo "================================================================"
  echo ""
  echo "graph_path = \"bonsai.db\""
  echo ""
  echo "[[target]]"
  echo "address    = \"172.100.102.11:57400\""
  echo "hostname   = \"srl-spine1\""
  echo "tls_domain = \"clab-bonsai-p4-srl-spine1\""
  echo "ca_cert    = \"lab/fast-iteration/p4-ca.pem\""
  echo "username   = \"admin\""
  echo "password   = \"NokiaSrl1!\""
  echo ""
  echo "[[target]]"
  echo "address    = \"172.100.102.12:57400\""
  echo "hostname   = \"srl-leaf1\""
  echo "tls_domain = \"clab-bonsai-p4-srl-leaf1\""
  echo "ca_cert    = \"lab/fast-iteration/p4-ca.pem\""
  echo "username   = \"admin\""
  echo "password   = \"NokiaSrl1!\""
  echo ""
  echo "[[target]]"
  echo "address    = \"172.100.102.13:57400\""
  echo "hostname   = \"srl-leaf2\""
  echo "tls_domain = \"clab-bonsai-p4-srl-leaf2\""
  echo "ca_cert    = \"lab/fast-iteration/p4-ca.pem\""
  echo "username   = \"admin\""
  echo "password   = \"NokiaSrl1!\""
  echo ""
  echo "[[target]]"
  echo "address  = \"172.100.102.21:57400\""
  echo "hostname = \"xrd-pe1\""
  echo "username = \"cisco\""
  echo "password = \"cisco123!\""
  echo ""
  echo "================================================================"
  echo ""
  echo "SSH access (XRd needs ~5 min after boot):"
  echo "  ssh admin@172.100.102.11    # srl-spine1  pass: NokiaSrl1!"
  echo "  ssh admin@172.100.102.12    # srl-leaf1   pass: NokiaSrl1!"
  echo "  ssh admin@172.100.102.13    # srl-leaf2   pass: NokiaSrl1!"
  echo "  ssh cisco@172.100.102.21    # xrd-pe1     pass: cisco123!"
  echo ""
  echo "Fault injection examples:"
  echo "  clab tools netem set bonsai-p4 srl-spine1 e1-1 --delay 500ms  # BGP flap on spine-leaf1 link"
  echo "  clab tools netem set bonsai-p4 srl-spine1 e1-1 --delay 0ms    # Restore"
  echo "  ssh admin@172.100.102.11 'sr_cli \"set / interface ethernet-1/1 admin-state disable\"'"
}

# ── main ──────────────────────────────────────────────────────────────────────

case "$ACTION" in
  deploy)
    do_deploy
    ;;
  destroy)
    do_destroy
    ;;
  reconfigure)
    do_destroy
    do_deploy
    ;;
  *)
    echo "Usage: $0 [deploy|destroy|reconfigure]"
    exit 1
    ;;
esac
