{{- if and .Values.persistence.enabled (ne .Values.mode "ha") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bonsai.archivePvcName" . }}
  labels:
    {{- include "bonsai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.archive.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bonsai.graphPvcName" . }}
  labels:
    {{- include "bonsai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.graph.size }}
{{- end }}
