{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bonsai.fullname" . }}-credentials
  labels:
    {{- include "bonsai.labels" . | nindent 4 }}
type: Opaque
stringData:
  BONSAI_VAULT_PASSPHRASE: {{ .Values.secrets.credentialPassphrase | default "" | quote }}
{{- end }}
