apiVersion: v1
kind: Service
metadata:
  name: {{ include "bonsai.fullname" . }}
  labels:
    {{- include "bonsai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.ports.metrics }}
    - port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "bonsai.selectorLabels" . | nindent 4 }}
