#!/usr/bin/env bash
# scripts/configure_external.sh — Auto-generate bonsai enrichment + adapter config
# from .env and the running external service state.
#
# Reads: .env (or exported env vars)
# Writes: docker/configs/core.toml.generated
#         (copy relevant sections into your active bonsai.toml)
#
# Usage:
#   source .env && scripts/configure_external.sh [--check-only]
#   # Then inspect docker/configs/core.toml.generated and merge into bonsai.toml

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${REPO_ROOT}/docker/configs/core.toml.generated"
CHECK_ONLY=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check-only) CHECK_ONLY=true ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
    shift
done

log() { echo "[$(date +%H:%M:%S)] $*"; }

log "=== Bonsai external config generator ==="

NETBOX_URL="${NETBOX_URL:-http://localhost:8000}"
NETBOX_TOKEN="${NETBOX_API_TOKEN:-bonsai-dev-token}"
SPLUNK_HEC_URL="http://localhost:8088"
SPLUNK_TOKEN="${SPLUNK_HEC_TOKEN:-}"
ELASTIC_URL="http://localhost:9200"
PROM_REMOTE_WRITE="http://localhost:9093/api/v1/write"
SNOW_URL="${SNOW_INSTANCE_URL:-}"
SNOW_USER="${SNOW_USERNAME:-}"

# Detect which services are actually reachable
NETBOX_OK=false
SPLUNK_OK=false
ELASTIC_OK=false
PROM_OK=false
SNOW_OK=false

curl -sf "${NETBOX_URL}/api/" -H "Authorization: Token ${NETBOX_TOKEN}" -o /dev/null 2>&1 && NETBOX_OK=true || true
curl -sf "${SPLUNK_HEC_URL}/services/collector/health" -o /dev/null 2>&1 && SPLUNK_OK=true || true
curl -sf "${ELASTIC_URL}/_cluster/health" -o /dev/null 2>&1 && ELASTIC_OK=true || true
curl -sf "http://localhost:9093/-/ready" -o /dev/null 2>&1 && PROM_OK=true || true
[[ -n "$SNOW_URL" ]] && curl -sf "${SNOW_URL}/api/now/table/cmdb_ci" -u "${SNOW_USER}:${SNOW_PASSWORD:-}" -o /dev/null 2>&1 && SNOW_OK=true || true

log "Service reachability:"
log "  NetBox:          $NETBOX_OK  (${NETBOX_URL})"
log "  Splunk HEC:      $SPLUNK_OK  (${SPLUNK_HEC_URL})"
log "  Elasticsearch:   $ELASTIC_OK (${ELASTIC_URL})"
log "  Prometheus:      $PROM_OK    (http://localhost:9093)"
log "  ServiceNow PDI:  $SNOW_OK    (${SNOW_URL:-not configured})"

[[ "$CHECK_ONLY" == "true" ]] && exit 0

# Generate the config sections
cat > "$OUTPUT" <<TOML
# AUTO-GENERATED by scripts/configure_external.sh — $(date)
# Do not edit this file directly. Re-run the script after changing .env or
# starting/stopping external services.
#
# Merge these sections into your active bonsai.toml (or docker/configs/all.toml)
# to enable the corresponding integrations.

TOML

if [[ "$NETBOX_OK" == "true" ]]; then
    cat >> "$OUTPUT" <<TOML
[enrichment.netbox]
url           = "${NETBOX_URL}"
token_env     = "NETBOX_API_TOKEN"
sync_interval_secs = 300
enabled       = true

TOML
    log "  wrote [enrichment.netbox]"
fi

if [[ "$SNOW_OK" == "true" ]]; then
    cat >> "$OUTPUT" <<TOML
[integrations.servicenow]
instance_url  = "${SNOW_URL}"
username_env  = "SNOW_USERNAME"
password_env  = "SNOW_PASSWORD"
sync_interval_secs = 600
enabled       = true

TOML
    log "  wrote [integrations.servicenow]"
fi

if [[ "$PROM_OK" == "true" ]]; then
    cat >> "$OUTPUT" <<TOML
# Add this adapter via POST /api/adapters or include at startup
# [[output_adapters]]
# name              = "prometheus-external"
# adapter_type      = "prometheus_remote_write"
# endpoint_url      = "${PROM_REMOTE_WRITE}"
# flush_interval_secs = 15
# enabled           = true

TOML
    log "  wrote prometheus adapter hint"
fi

if [[ "$SPLUNK_OK" == "true" && -n "$SPLUNK_TOKEN" ]]; then
    cat >> "$OUTPUT" <<TOML
# [[output_adapters]]
# name              = "splunk-external"
# adapter_type      = "splunk_hec"
# endpoint_url      = "${SPLUNK_HEC_URL}/services/collector"
# flush_interval_secs = 15
# enabled           = true
# [output_adapters.extra]
# hec_token_env     = "SPLUNK_HEC_TOKEN"

TOML
    log "  wrote splunk adapter hint"
fi

if [[ "$ELASTIC_OK" == "true" ]]; then
    cat >> "$OUTPUT" <<TOML
# [[output_adapters]]
# name              = "elastic-external"
# adapter_type      = "elasticsearch"
# endpoint_url      = "${ELASTIC_URL}"
# flush_interval_secs = 15
# enabled           = true

TOML
    log "  wrote elastic adapter hint"
fi

log ""
log "Generated: $OUTPUT"
log "Review the file and merge the relevant sections into your bonsai.toml."
